"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getLeagueBySummonerIdApi = exports.getMatchByMatchIdApi = exports.getMatchIdsByPuuidApi = exports.getPlatformDataApi = exports.getCurrentGameBySummonerIdApi = exports.getFeaturedGameApi = exports.getSummonerByNameApi = exports.getRotationApi = void 0;
// API Routes에서 라이엇 api에 요청을 보낼 때 사용하는 api 목록
const _1 = require(".");
const getRotationApi = () => _1.axiosRiotKr.get("/lol/platform/v3/champion-rotations");
exports.getRotationApi = getRotationApi;
const getSummonerByNameApi = (summonerName) => _1.axiosRiotKr.get(`/lol/summoner/v4/summoners/by-name/${encodeURIComponent(summonerName)}`);
exports.getSummonerByNameApi = getSummonerByNameApi;
const getFeaturedGameApi = () => _1.axiosRiotKr.get("/lol/spectator/v4/featured-games");
exports.getFeaturedGameApi = getFeaturedGameApi;
const getCurrentGameBySummonerIdApi = (summonerId) => _1.axiosRiotKr.get(`/lol/spectator/v4/active-games/by-summoner/${summonerId}`);
exports.getCurrentGameBySummonerIdApi = getCurrentGameBySummonerIdApi;
const getPlatformDataApi = () => _1.axiosRiotKr.get("/lol/status/v4/platform-data");
exports.getPlatformDataApi = getPlatformDataApi;
const getMatchIdsByPuuidApi = (puuid) => _1.axiosRiotAsia.get(`/lol/match/v5/matches/by-puuid/${puuid}/ids`);
exports.getMatchIdsByPuuidApi = getMatchIdsByPuuidApi;
const getMatchByMatchIdApi = (matchId) => _1.axiosRiotAsia.get(`lol/match/v5/matches/${matchId}`);
exports.getMatchByMatchIdApi = getMatchByMatchIdApi;
const getLeagueBySummonerIdApi = (summonerId) => _1.axiosRiotKr.get(`/lol/league/v4/entries/by-summoner/${summonerId}`);
exports.getLeagueBySummonerIdApi = getLeagueBySummonerIdApi;
